services:
  logto-go:
    build:
      context: .
      dockerfile_inline: |
        FROM golang:1.22-alpine
        RUN apk add git
        WORKDIR /app
        RUN git clone https://github.com/logto-io/go.git
        WORKDIR /app/go/gin-sample
        RUN go mod download

        ENV ENDPOINT=<your-logto-endpoint>
        ENV APP_ID=<your-app-id>
        ENV APP_SECRET=<your-app-secret>
        ENV RESOURCES=<your-resources>
        ENV CALLBACK_URI=<your-callback-uri>
        ENV POST_LOGOUT_REDIRECT_URI=<your-post-logout-redirect-uri>

        CMD go run .
    ports:
      - 8080:8080
