/*
Logto API references

API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.

API version: Cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package logto

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetSignInExperienceConfig200ResponseSocialConnectorsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSignInExperienceConfig200ResponseSocialConnectorsInner{}

// GetSignInExperienceConfig200ResponseSocialConnectorsInner struct for GetSignInExperienceConfig200ResponseSocialConnectorsInner
type GetSignInExperienceConfig200ResponseSocialConnectorsInner struct {
	Id string `json:"id"`
	Target string `json:"target"`
	// Validator function
	Name map[string]interface{} `json:"name"`
	Logo string `json:"logo"`
	LogoDark NullableString `json:"logoDark"`
	FromEmail *string `json:"fromEmail,omitempty"`
	Platform NullableString `json:"platform"`
	IsStandard *bool `json:"isStandard,omitempty"`
}

type _GetSignInExperienceConfig200ResponseSocialConnectorsInner GetSignInExperienceConfig200ResponseSocialConnectorsInner

// NewGetSignInExperienceConfig200ResponseSocialConnectorsInner instantiates a new GetSignInExperienceConfig200ResponseSocialConnectorsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSignInExperienceConfig200ResponseSocialConnectorsInner(id string, target string, name map[string]interface{}, logo string, logoDark NullableString, platform NullableString) *GetSignInExperienceConfig200ResponseSocialConnectorsInner {
	this := GetSignInExperienceConfig200ResponseSocialConnectorsInner{}
	this.Id = id
	this.Target = target
	this.Name = name
	this.Logo = logo
	this.LogoDark = logoDark
	this.Platform = platform
	return &this
}

// NewGetSignInExperienceConfig200ResponseSocialConnectorsInnerWithDefaults instantiates a new GetSignInExperienceConfig200ResponseSocialConnectorsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSignInExperienceConfig200ResponseSocialConnectorsInnerWithDefaults() *GetSignInExperienceConfig200ResponseSocialConnectorsInner {
	this := GetSignInExperienceConfig200ResponseSocialConnectorsInner{}
	return &this
}

// GetId returns the Id field value
func (o *GetSignInExperienceConfig200ResponseSocialConnectorsInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetSignInExperienceConfig200ResponseSocialConnectorsInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetSignInExperienceConfig200ResponseSocialConnectorsInner) SetId(v string) {
	o.Id = v
}

// GetTarget returns the Target field value
func (o *GetSignInExperienceConfig200ResponseSocialConnectorsInner) GetTarget() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Target
}

// GetTargetOk returns a tuple with the Target field value
// and a boolean to check if the value has been set.
func (o *GetSignInExperienceConfig200ResponseSocialConnectorsInner) GetTargetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Target, true
}

// SetTarget sets field value
func (o *GetSignInExperienceConfig200ResponseSocialConnectorsInner) SetTarget(v string) {
	o.Target = v
}

// GetName returns the Name field value
func (o *GetSignInExperienceConfig200ResponseSocialConnectorsInner) GetName() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetSignInExperienceConfig200ResponseSocialConnectorsInner) GetNameOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Name, true
}

// SetName sets field value
func (o *GetSignInExperienceConfig200ResponseSocialConnectorsInner) SetName(v map[string]interface{}) {
	o.Name = v
}

// GetLogo returns the Logo field value
func (o *GetSignInExperienceConfig200ResponseSocialConnectorsInner) GetLogo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Logo
}

// GetLogoOk returns a tuple with the Logo field value
// and a boolean to check if the value has been set.
func (o *GetSignInExperienceConfig200ResponseSocialConnectorsInner) GetLogoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Logo, true
}

// SetLogo sets field value
func (o *GetSignInExperienceConfig200ResponseSocialConnectorsInner) SetLogo(v string) {
	o.Logo = v
}

// GetLogoDark returns the LogoDark field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetSignInExperienceConfig200ResponseSocialConnectorsInner) GetLogoDark() string {
	if o == nil || o.LogoDark.Get() == nil {
		var ret string
		return ret
	}

	return *o.LogoDark.Get()
}

// GetLogoDarkOk returns a tuple with the LogoDark field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetSignInExperienceConfig200ResponseSocialConnectorsInner) GetLogoDarkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LogoDark.Get(), o.LogoDark.IsSet()
}

// SetLogoDark sets field value
func (o *GetSignInExperienceConfig200ResponseSocialConnectorsInner) SetLogoDark(v string) {
	o.LogoDark.Set(&v)
}

// GetFromEmail returns the FromEmail field value if set, zero value otherwise.
func (o *GetSignInExperienceConfig200ResponseSocialConnectorsInner) GetFromEmail() string {
	if o == nil || IsNil(o.FromEmail) {
		var ret string
		return ret
	}
	return *o.FromEmail
}

// GetFromEmailOk returns a tuple with the FromEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSignInExperienceConfig200ResponseSocialConnectorsInner) GetFromEmailOk() (*string, bool) {
	if o == nil || IsNil(o.FromEmail) {
		return nil, false
	}
	return o.FromEmail, true
}

// HasFromEmail returns a boolean if a field has been set.
func (o *GetSignInExperienceConfig200ResponseSocialConnectorsInner) HasFromEmail() bool {
	if o != nil && !IsNil(o.FromEmail) {
		return true
	}

	return false
}

// SetFromEmail gets a reference to the given string and assigns it to the FromEmail field.
func (o *GetSignInExperienceConfig200ResponseSocialConnectorsInner) SetFromEmail(v string) {
	o.FromEmail = &v
}

// GetPlatform returns the Platform field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetSignInExperienceConfig200ResponseSocialConnectorsInner) GetPlatform() string {
	if o == nil || o.Platform.Get() == nil {
		var ret string
		return ret
	}

	return *o.Platform.Get()
}

// GetPlatformOk returns a tuple with the Platform field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetSignInExperienceConfig200ResponseSocialConnectorsInner) GetPlatformOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Platform.Get(), o.Platform.IsSet()
}

// SetPlatform sets field value
func (o *GetSignInExperienceConfig200ResponseSocialConnectorsInner) SetPlatform(v string) {
	o.Platform.Set(&v)
}

// GetIsStandard returns the IsStandard field value if set, zero value otherwise.
func (o *GetSignInExperienceConfig200ResponseSocialConnectorsInner) GetIsStandard() bool {
	if o == nil || IsNil(o.IsStandard) {
		var ret bool
		return ret
	}
	return *o.IsStandard
}

// GetIsStandardOk returns a tuple with the IsStandard field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSignInExperienceConfig200ResponseSocialConnectorsInner) GetIsStandardOk() (*bool, bool) {
	if o == nil || IsNil(o.IsStandard) {
		return nil, false
	}
	return o.IsStandard, true
}

// HasIsStandard returns a boolean if a field has been set.
func (o *GetSignInExperienceConfig200ResponseSocialConnectorsInner) HasIsStandard() bool {
	if o != nil && !IsNil(o.IsStandard) {
		return true
	}

	return false
}

// SetIsStandard gets a reference to the given bool and assigns it to the IsStandard field.
func (o *GetSignInExperienceConfig200ResponseSocialConnectorsInner) SetIsStandard(v bool) {
	o.IsStandard = &v
}

func (o GetSignInExperienceConfig200ResponseSocialConnectorsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSignInExperienceConfig200ResponseSocialConnectorsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["target"] = o.Target
	toSerialize["name"] = o.Name
	toSerialize["logo"] = o.Logo
	toSerialize["logoDark"] = o.LogoDark.Get()
	if !IsNil(o.FromEmail) {
		toSerialize["fromEmail"] = o.FromEmail
	}
	toSerialize["platform"] = o.Platform.Get()
	if !IsNil(o.IsStandard) {
		toSerialize["isStandard"] = o.IsStandard
	}
	return toSerialize, nil
}

func (o *GetSignInExperienceConfig200ResponseSocialConnectorsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"target",
		"name",
		"logo",
		"logoDark",
		"platform",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetSignInExperienceConfig200ResponseSocialConnectorsInner := _GetSignInExperienceConfig200ResponseSocialConnectorsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetSignInExperienceConfig200ResponseSocialConnectorsInner)

	if err != nil {
		return err
	}

	*o = GetSignInExperienceConfig200ResponseSocialConnectorsInner(varGetSignInExperienceConfig200ResponseSocialConnectorsInner)

	return err
}

type NullableGetSignInExperienceConfig200ResponseSocialConnectorsInner struct {
	value *GetSignInExperienceConfig200ResponseSocialConnectorsInner
	isSet bool
}

func (v NullableGetSignInExperienceConfig200ResponseSocialConnectorsInner) Get() *GetSignInExperienceConfig200ResponseSocialConnectorsInner {
	return v.value
}

func (v *NullableGetSignInExperienceConfig200ResponseSocialConnectorsInner) Set(val *GetSignInExperienceConfig200ResponseSocialConnectorsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSignInExperienceConfig200ResponseSocialConnectorsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSignInExperienceConfig200ResponseSocialConnectorsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSignInExperienceConfig200ResponseSocialConnectorsInner(val *GetSignInExperienceConfig200ResponseSocialConnectorsInner) *NullableGetSignInExperienceConfig200ResponseSocialConnectorsInner {
	return &NullableGetSignInExperienceConfig200ResponseSocialConnectorsInner{value: val, isSet: true}
}

func (v NullableGetSignInExperienceConfig200ResponseSocialConnectorsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSignInExperienceConfig200ResponseSocialConnectorsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


