/*
Logto API references

API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.

API version: Cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package logto

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner{}

// CreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner struct for CreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner
type CreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner struct {
	Type string `json:"type"`
	Id string `json:"id"`
	Transports []string `json:"transports,omitempty"`
}

type _CreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner CreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner

// NewCreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner instantiates a new CreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner(type_ string, id string) *CreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner {
	this := CreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner{}
	this.Type = type_
	this.Id = id
	return &this
}

// NewCreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInnerWithDefaults instantiates a new CreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInnerWithDefaults() *CreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner {
	this := CreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner{}
	return &this
}

// GetType returns the Type field value
func (o *CreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner) SetType(v string) {
	o.Type = v
}

// GetId returns the Id field value
func (o *CreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner) SetId(v string) {
	o.Id = v
}

// GetTransports returns the Transports field value if set, zero value otherwise.
func (o *CreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner) GetTransports() []string {
	if o == nil || IsNil(o.Transports) {
		var ret []string
		return ret
	}
	return o.Transports
}

// GetTransportsOk returns a tuple with the Transports field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner) GetTransportsOk() ([]string, bool) {
	if o == nil || IsNil(o.Transports) {
		return nil, false
	}
	return o.Transports, true
}

// HasTransports returns a boolean if a field has been set.
func (o *CreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner) HasTransports() bool {
	if o != nil && !IsNil(o.Transports) {
		return true
	}

	return false
}

// SetTransports gets a reference to the given []string and assigns it to the Transports field.
func (o *CreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner) SetTransports(v []string) {
	o.Transports = v
}

func (o CreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["id"] = o.Id
	if !IsNil(o.Transports) {
		toSerialize["transports"] = o.Transports
	}
	return toSerialize, nil
}

func (o *CreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner := _CreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner)

	if err != nil {
		return err
	}

	*o = CreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner(varCreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner)

	return err
}

type NullableCreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner struct {
	value *CreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner
	isSet bool
}

func (v NullableCreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner) Get() *CreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner {
	return v.value
}

func (v *NullableCreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner) Set(val *CreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner(val *CreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner) *NullableCreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner {
	return &NullableCreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner{value: val, isSet: true}
}

func (v NullableCreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateWebAuthnRegistrationVerification200ResponseRegistrationOptionsExcludeCredentialsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


