/*
Logto API references

API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.

API version: Cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package logto

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateApplicationUserConsentOrganizationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateApplicationUserConsentOrganizationRequest{}

// CreateApplicationUserConsentOrganizationRequest struct for CreateApplicationUserConsentOrganizationRequest
type CreateApplicationUserConsentOrganizationRequest struct {
	// A list of organization ids to be granted.
	OrganizationIds []string `json:"organizationIds"`
}

type _CreateApplicationUserConsentOrganizationRequest CreateApplicationUserConsentOrganizationRequest

// NewCreateApplicationUserConsentOrganizationRequest instantiates a new CreateApplicationUserConsentOrganizationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateApplicationUserConsentOrganizationRequest(organizationIds []string) *CreateApplicationUserConsentOrganizationRequest {
	this := CreateApplicationUserConsentOrganizationRequest{}
	this.OrganizationIds = organizationIds
	return &this
}

// NewCreateApplicationUserConsentOrganizationRequestWithDefaults instantiates a new CreateApplicationUserConsentOrganizationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateApplicationUserConsentOrganizationRequestWithDefaults() *CreateApplicationUserConsentOrganizationRequest {
	this := CreateApplicationUserConsentOrganizationRequest{}
	return &this
}

// GetOrganizationIds returns the OrganizationIds field value
func (o *CreateApplicationUserConsentOrganizationRequest) GetOrganizationIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.OrganizationIds
}

// GetOrganizationIdsOk returns a tuple with the OrganizationIds field value
// and a boolean to check if the value has been set.
func (o *CreateApplicationUserConsentOrganizationRequest) GetOrganizationIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrganizationIds, true
}

// SetOrganizationIds sets field value
func (o *CreateApplicationUserConsentOrganizationRequest) SetOrganizationIds(v []string) {
	o.OrganizationIds = v
}

func (o CreateApplicationUserConsentOrganizationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateApplicationUserConsentOrganizationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["organizationIds"] = o.OrganizationIds
	return toSerialize, nil
}

func (o *CreateApplicationUserConsentOrganizationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"organizationIds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateApplicationUserConsentOrganizationRequest := _CreateApplicationUserConsentOrganizationRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateApplicationUserConsentOrganizationRequest)

	if err != nil {
		return err
	}

	*o = CreateApplicationUserConsentOrganizationRequest(varCreateApplicationUserConsentOrganizationRequest)

	return err
}

type NullableCreateApplicationUserConsentOrganizationRequest struct {
	value *CreateApplicationUserConsentOrganizationRequest
	isSet bool
}

func (v NullableCreateApplicationUserConsentOrganizationRequest) Get() *CreateApplicationUserConsentOrganizationRequest {
	return v.value
}

func (v *NullableCreateApplicationUserConsentOrganizationRequest) Set(val *CreateApplicationUserConsentOrganizationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateApplicationUserConsentOrganizationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateApplicationUserConsentOrganizationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateApplicationUserConsentOrganizationRequest(val *CreateApplicationUserConsentOrganizationRequest) *NullableCreateApplicationUserConsentOrganizationRequest {
	return &NullableCreateApplicationUserConsentOrganizationRequest{value: val, isSet: true}
}

func (v NullableCreateApplicationUserConsentOrganizationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateApplicationUserConsentOrganizationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


