/*
Logto API references

API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.

API version: Cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package logto

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateOrganizationScopeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrganizationScopeRequest{}

// CreateOrganizationScopeRequest struct for CreateOrganizationScopeRequest
type CreateOrganizationScopeRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	// The name of the organization scope. It must be unique within the organization template.
	Name string `json:"name"`
	// The description of the organization scope.
	Description NullableString `json:"description,omitempty"`
}

type _CreateOrganizationScopeRequest CreateOrganizationScopeRequest

// NewCreateOrganizationScopeRequest instantiates a new CreateOrganizationScopeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrganizationScopeRequest(name string) *CreateOrganizationScopeRequest {
	this := CreateOrganizationScopeRequest{}
	this.Name = name
	return &this
}

// NewCreateOrganizationScopeRequestWithDefaults instantiates a new CreateOrganizationScopeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrganizationScopeRequestWithDefaults() *CreateOrganizationScopeRequest {
	this := CreateOrganizationScopeRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *CreateOrganizationScopeRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrganizationScopeRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *CreateOrganizationScopeRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *CreateOrganizationScopeRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetName returns the Name field value
func (o *CreateOrganizationScopeRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateOrganizationScopeRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateOrganizationScopeRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOrganizationScopeRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrganizationScopeRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateOrganizationScopeRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *CreateOrganizationScopeRequest) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *CreateOrganizationScopeRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *CreateOrganizationScopeRequest) UnsetDescription() {
	o.Description.Unset()
}

func (o CreateOrganizationScopeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrganizationScopeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	toSerialize["name"] = o.Name
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	return toSerialize, nil
}

func (o *CreateOrganizationScopeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOrganizationScopeRequest := _CreateOrganizationScopeRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateOrganizationScopeRequest)

	if err != nil {
		return err
	}

	*o = CreateOrganizationScopeRequest(varCreateOrganizationScopeRequest)

	return err
}

type NullableCreateOrganizationScopeRequest struct {
	value *CreateOrganizationScopeRequest
	isSet bool
}

func (v NullableCreateOrganizationScopeRequest) Get() *CreateOrganizationScopeRequest {
	return v.value
}

func (v *NullableCreateOrganizationScopeRequest) Set(val *CreateOrganizationScopeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrganizationScopeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrganizationScopeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrganizationScopeRequest(val *CreateOrganizationScopeRequest) *NullableCreateOrganizationScopeRequest {
	return &NullableCreateOrganizationScopeRequest{value: val, isSet: true}
}

func (v NullableCreateOrganizationScopeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrganizationScopeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


