/*
Logto API references

API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.

API version: Cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package logto

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateSocialVerification200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSocialVerification200Response{}

// CreateSocialVerification200Response struct for CreateSocialVerification200Response
type CreateSocialVerification200Response struct {
	// The social authorization URI.
	AuthorizationUri string `json:"authorizationUri"`
	// The unique verification ID of the newly created SocialVerification record. The `verificationId` is required when verifying the social authorization response.
	VerificationId string `json:"verificationId"`
}

type _CreateSocialVerification200Response CreateSocialVerification200Response

// NewCreateSocialVerification200Response instantiates a new CreateSocialVerification200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSocialVerification200Response(authorizationUri string, verificationId string) *CreateSocialVerification200Response {
	this := CreateSocialVerification200Response{}
	this.AuthorizationUri = authorizationUri
	this.VerificationId = verificationId
	return &this
}

// NewCreateSocialVerification200ResponseWithDefaults instantiates a new CreateSocialVerification200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSocialVerification200ResponseWithDefaults() *CreateSocialVerification200Response {
	this := CreateSocialVerification200Response{}
	return &this
}

// GetAuthorizationUri returns the AuthorizationUri field value
func (o *CreateSocialVerification200Response) GetAuthorizationUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthorizationUri
}

// GetAuthorizationUriOk returns a tuple with the AuthorizationUri field value
// and a boolean to check if the value has been set.
func (o *CreateSocialVerification200Response) GetAuthorizationUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthorizationUri, true
}

// SetAuthorizationUri sets field value
func (o *CreateSocialVerification200Response) SetAuthorizationUri(v string) {
	o.AuthorizationUri = v
}

// GetVerificationId returns the VerificationId field value
func (o *CreateSocialVerification200Response) GetVerificationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VerificationId
}

// GetVerificationIdOk returns a tuple with the VerificationId field value
// and a boolean to check if the value has been set.
func (o *CreateSocialVerification200Response) GetVerificationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VerificationId, true
}

// SetVerificationId sets field value
func (o *CreateSocialVerification200Response) SetVerificationId(v string) {
	o.VerificationId = v
}

func (o CreateSocialVerification200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSocialVerification200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["authorizationUri"] = o.AuthorizationUri
	toSerialize["verificationId"] = o.VerificationId
	return toSerialize, nil
}

func (o *CreateSocialVerification200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"authorizationUri",
		"verificationId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateSocialVerification200Response := _CreateSocialVerification200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateSocialVerification200Response)

	if err != nil {
		return err
	}

	*o = CreateSocialVerification200Response(varCreateSocialVerification200Response)

	return err
}

type NullableCreateSocialVerification200Response struct {
	value *CreateSocialVerification200Response
	isSet bool
}

func (v NullableCreateSocialVerification200Response) Get() *CreateSocialVerification200Response {
	return v.value
}

func (v *NullableCreateSocialVerification200Response) Set(val *CreateSocialVerification200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSocialVerification200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSocialVerification200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSocialVerification200Response(val *CreateSocialVerification200Response) *NullableCreateSocialVerification200Response {
	return &NullableCreateSocialVerification200Response{value: val, isSet: true}
}

func (v NullableCreateSocialVerification200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSocialVerification200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


