/*
Logto API references

API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.

API version: Cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package logto

import (
	"encoding/json"
)

// checks if the ApiInteractionPutRequestProfile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiInteractionPutRequestProfile{}

// ApiInteractionPutRequestProfile struct for ApiInteractionPutRequestProfile
type ApiInteractionPutRequestProfile struct {
	Username *string `json:"username,omitempty" validate:"regexp=^[A-Z_a-z]\\\\w*$"`
	Email *string `json:"email,omitempty" validate:"regexp=^\\\\S+@\\\\S+\\\\.\\\\S+$"`
	Phone *string `json:"phone,omitempty" validate:"regexp=^\\\\d+$"`
	ConnectorId *string `json:"connectorId,omitempty"`
	Password *string `json:"password,omitempty"`
}

// NewApiInteractionPutRequestProfile instantiates a new ApiInteractionPutRequestProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiInteractionPutRequestProfile() *ApiInteractionPutRequestProfile {
	this := ApiInteractionPutRequestProfile{}
	return &this
}

// NewApiInteractionPutRequestProfileWithDefaults instantiates a new ApiInteractionPutRequestProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiInteractionPutRequestProfileWithDefaults() *ApiInteractionPutRequestProfile {
	this := ApiInteractionPutRequestProfile{}
	return &this
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *ApiInteractionPutRequestProfile) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiInteractionPutRequestProfile) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *ApiInteractionPutRequestProfile) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *ApiInteractionPutRequestProfile) SetUsername(v string) {
	o.Username = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *ApiInteractionPutRequestProfile) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiInteractionPutRequestProfile) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *ApiInteractionPutRequestProfile) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *ApiInteractionPutRequestProfile) SetEmail(v string) {
	o.Email = &v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *ApiInteractionPutRequestProfile) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiInteractionPutRequestProfile) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *ApiInteractionPutRequestProfile) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *ApiInteractionPutRequestProfile) SetPhone(v string) {
	o.Phone = &v
}

// GetConnectorId returns the ConnectorId field value if set, zero value otherwise.
func (o *ApiInteractionPutRequestProfile) GetConnectorId() string {
	if o == nil || IsNil(o.ConnectorId) {
		var ret string
		return ret
	}
	return *o.ConnectorId
}

// GetConnectorIdOk returns a tuple with the ConnectorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiInteractionPutRequestProfile) GetConnectorIdOk() (*string, bool) {
	if o == nil || IsNil(o.ConnectorId) {
		return nil, false
	}
	return o.ConnectorId, true
}

// HasConnectorId returns a boolean if a field has been set.
func (o *ApiInteractionPutRequestProfile) HasConnectorId() bool {
	if o != nil && !IsNil(o.ConnectorId) {
		return true
	}

	return false
}

// SetConnectorId gets a reference to the given string and assigns it to the ConnectorId field.
func (o *ApiInteractionPutRequestProfile) SetConnectorId(v string) {
	o.ConnectorId = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *ApiInteractionPutRequestProfile) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiInteractionPutRequestProfile) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *ApiInteractionPutRequestProfile) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *ApiInteractionPutRequestProfile) SetPassword(v string) {
	o.Password = &v
}

func (o ApiInteractionPutRequestProfile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiInteractionPutRequestProfile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	if !IsNil(o.ConnectorId) {
		toSerialize["connectorId"] = o.ConnectorId
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	return toSerialize, nil
}

type NullableApiInteractionPutRequestProfile struct {
	value *ApiInteractionPutRequestProfile
	isSet bool
}

func (v NullableApiInteractionPutRequestProfile) Get() *ApiInteractionPutRequestProfile {
	return v.value
}

func (v *NullableApiInteractionPutRequestProfile) Set(val *ApiInteractionPutRequestProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableApiInteractionPutRequestProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableApiInteractionPutRequestProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiInteractionPutRequestProfile(val *ApiInteractionPutRequestProfile) *NullableApiInteractionPutRequestProfile {
	return &NullableApiInteractionPutRequestProfile{value: val, isSet: true}
}

func (v NullableApiInteractionPutRequestProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiInteractionPutRequestProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


