/*
Logto API references

API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.

API version: Cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package logto

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateUserMfaVerification200ResponseOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateUserMfaVerification200ResponseOneOf1{}

// CreateUserMfaVerification200ResponseOneOf1 struct for CreateUserMfaVerification200ResponseOneOf1
type CreateUserMfaVerification200ResponseOneOf1 struct {
	Type string `json:"type"`
	Codes []string `json:"codes"`
}

type _CreateUserMfaVerification200ResponseOneOf1 CreateUserMfaVerification200ResponseOneOf1

// NewCreateUserMfaVerification200ResponseOneOf1 instantiates a new CreateUserMfaVerification200ResponseOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateUserMfaVerification200ResponseOneOf1(type_ string, codes []string) *CreateUserMfaVerification200ResponseOneOf1 {
	this := CreateUserMfaVerification200ResponseOneOf1{}
	this.Type = type_
	this.Codes = codes
	return &this
}

// NewCreateUserMfaVerification200ResponseOneOf1WithDefaults instantiates a new CreateUserMfaVerification200ResponseOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateUserMfaVerification200ResponseOneOf1WithDefaults() *CreateUserMfaVerification200ResponseOneOf1 {
	this := CreateUserMfaVerification200ResponseOneOf1{}
	return &this
}

// GetType returns the Type field value
func (o *CreateUserMfaVerification200ResponseOneOf1) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateUserMfaVerification200ResponseOneOf1) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateUserMfaVerification200ResponseOneOf1) SetType(v string) {
	o.Type = v
}

// GetCodes returns the Codes field value
func (o *CreateUserMfaVerification200ResponseOneOf1) GetCodes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Codes
}

// GetCodesOk returns a tuple with the Codes field value
// and a boolean to check if the value has been set.
func (o *CreateUserMfaVerification200ResponseOneOf1) GetCodesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Codes, true
}

// SetCodes sets field value
func (o *CreateUserMfaVerification200ResponseOneOf1) SetCodes(v []string) {
	o.Codes = v
}

func (o CreateUserMfaVerification200ResponseOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateUserMfaVerification200ResponseOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["codes"] = o.Codes
	return toSerialize, nil
}

func (o *CreateUserMfaVerification200ResponseOneOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"codes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateUserMfaVerification200ResponseOneOf1 := _CreateUserMfaVerification200ResponseOneOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateUserMfaVerification200ResponseOneOf1)

	if err != nil {
		return err
	}

	*o = CreateUserMfaVerification200ResponseOneOf1(varCreateUserMfaVerification200ResponseOneOf1)

	return err
}

type NullableCreateUserMfaVerification200ResponseOneOf1 struct {
	value *CreateUserMfaVerification200ResponseOneOf1
	isSet bool
}

func (v NullableCreateUserMfaVerification200ResponseOneOf1) Get() *CreateUserMfaVerification200ResponseOneOf1 {
	return v.value
}

func (v *NullableCreateUserMfaVerification200ResponseOneOf1) Set(val *CreateUserMfaVerification200ResponseOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateUserMfaVerification200ResponseOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateUserMfaVerification200ResponseOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateUserMfaVerification200ResponseOneOf1(val *CreateUserMfaVerification200ResponseOneOf1) *NullableCreateUserMfaVerification200ResponseOneOf1 {
	return &NullableCreateUserMfaVerification200ResponseOneOf1{value: val, isSet: true}
}

func (v NullableCreateUserMfaVerification200ResponseOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateUserMfaVerification200ResponseOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


