/*
Logto API references

API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.

API version: Cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package logto

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddOrganizationApplicationsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddOrganizationApplicationsRequest{}

// AddOrganizationApplicationsRequest struct for AddOrganizationApplicationsRequest
type AddOrganizationApplicationsRequest struct {
	// The application IDs to add.
	ApplicationIds []string `json:"applicationIds"`
}

type _AddOrganizationApplicationsRequest AddOrganizationApplicationsRequest

// NewAddOrganizationApplicationsRequest instantiates a new AddOrganizationApplicationsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddOrganizationApplicationsRequest(applicationIds []string) *AddOrganizationApplicationsRequest {
	this := AddOrganizationApplicationsRequest{}
	this.ApplicationIds = applicationIds
	return &this
}

// NewAddOrganizationApplicationsRequestWithDefaults instantiates a new AddOrganizationApplicationsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddOrganizationApplicationsRequestWithDefaults() *AddOrganizationApplicationsRequest {
	this := AddOrganizationApplicationsRequest{}
	return &this
}

// GetApplicationIds returns the ApplicationIds field value
func (o *AddOrganizationApplicationsRequest) GetApplicationIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ApplicationIds
}

// GetApplicationIdsOk returns a tuple with the ApplicationIds field value
// and a boolean to check if the value has been set.
func (o *AddOrganizationApplicationsRequest) GetApplicationIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ApplicationIds, true
}

// SetApplicationIds sets field value
func (o *AddOrganizationApplicationsRequest) SetApplicationIds(v []string) {
	o.ApplicationIds = v
}

func (o AddOrganizationApplicationsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddOrganizationApplicationsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["applicationIds"] = o.ApplicationIds
	return toSerialize, nil
}

func (o *AddOrganizationApplicationsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"applicationIds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddOrganizationApplicationsRequest := _AddOrganizationApplicationsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddOrganizationApplicationsRequest)

	if err != nil {
		return err
	}

	*o = AddOrganizationApplicationsRequest(varAddOrganizationApplicationsRequest)

	return err
}

type NullableAddOrganizationApplicationsRequest struct {
	value *AddOrganizationApplicationsRequest
	isSet bool
}

func (v NullableAddOrganizationApplicationsRequest) Get() *AddOrganizationApplicationsRequest {
	return v.value
}

func (v *NullableAddOrganizationApplicationsRequest) Set(val *AddOrganizationApplicationsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddOrganizationApplicationsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddOrganizationApplicationsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddOrganizationApplicationsRequest(val *AddOrganizationApplicationsRequest) *NullableAddOrganizationApplicationsRequest {
	return &NullableAddOrganizationApplicationsRequest{value: val, isSet: true}
}

func (v NullableAddOrganizationApplicationsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddOrganizationApplicationsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


