/*
Logto API references

API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.

API version: Cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package logto

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResetUserPasswordRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResetUserPasswordRequest{}

// ResetUserPasswordRequest struct for ResetUserPasswordRequest
type ResetUserPasswordRequest struct {
	// The new password to update. The password must meet the password policy requirements and can not be the same as the current password.
	Password string `json:"password"`
}

type _ResetUserPasswordRequest ResetUserPasswordRequest

// NewResetUserPasswordRequest instantiates a new ResetUserPasswordRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResetUserPasswordRequest(password string) *ResetUserPasswordRequest {
	this := ResetUserPasswordRequest{}
	this.Password = password
	return &this
}

// NewResetUserPasswordRequestWithDefaults instantiates a new ResetUserPasswordRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResetUserPasswordRequestWithDefaults() *ResetUserPasswordRequest {
	this := ResetUserPasswordRequest{}
	return &this
}

// GetPassword returns the Password field value
func (o *ResetUserPasswordRequest) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *ResetUserPasswordRequest) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *ResetUserPasswordRequest) SetPassword(v string) {
	o.Password = v
}

func (o ResetUserPasswordRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResetUserPasswordRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["password"] = o.Password
	return toSerialize, nil
}

func (o *ResetUserPasswordRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResetUserPasswordRequest := _ResetUserPasswordRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResetUserPasswordRequest)

	if err != nil {
		return err
	}

	*o = ResetUserPasswordRequest(varResetUserPasswordRequest)

	return err
}

type NullableResetUserPasswordRequest struct {
	value *ResetUserPasswordRequest
	isSet bool
}

func (v NullableResetUserPasswordRequest) Get() *ResetUserPasswordRequest {
	return v.value
}

func (v *NullableResetUserPasswordRequest) Set(val *ResetUserPasswordRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableResetUserPasswordRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableResetUserPasswordRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResetUserPasswordRequest(val *ResetUserPasswordRequest) *NullableResetUserPasswordRequest {
	return &NullableResetUserPasswordRequest{value: val, isSet: true}
}

func (v NullableResetUserPasswordRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResetUserPasswordRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


