/*
Logto API references

API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.

API version: Cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package logto

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// ApiInteractionBindMfaPostRequest - struct for ApiInteractionBindMfaPostRequest
type ApiInteractionBindMfaPostRequest struct {
	ApiInteractionBindMfaPostRequestOneOf *ApiInteractionBindMfaPostRequestOneOf
	ApiInteractionBindMfaPostRequestOneOf1 *ApiInteractionBindMfaPostRequestOneOf1
	ApiInteractionBindMfaPostRequestOneOf2 *ApiInteractionBindMfaPostRequestOneOf2
}

// ApiInteractionBindMfaPostRequestOneOfAsApiInteractionBindMfaPostRequest is a convenience function that returns ApiInteractionBindMfaPostRequestOneOf wrapped in ApiInteractionBindMfaPostRequest
func ApiInteractionBindMfaPostRequestOneOfAsApiInteractionBindMfaPostRequest(v *ApiInteractionBindMfaPostRequestOneOf) ApiInteractionBindMfaPostRequest {
	return ApiInteractionBindMfaPostRequest{
		ApiInteractionBindMfaPostRequestOneOf: v,
	}
}

// ApiInteractionBindMfaPostRequestOneOf1AsApiInteractionBindMfaPostRequest is a convenience function that returns ApiInteractionBindMfaPostRequestOneOf1 wrapped in ApiInteractionBindMfaPostRequest
func ApiInteractionBindMfaPostRequestOneOf1AsApiInteractionBindMfaPostRequest(v *ApiInteractionBindMfaPostRequestOneOf1) ApiInteractionBindMfaPostRequest {
	return ApiInteractionBindMfaPostRequest{
		ApiInteractionBindMfaPostRequestOneOf1: v,
	}
}

// ApiInteractionBindMfaPostRequestOneOf2AsApiInteractionBindMfaPostRequest is a convenience function that returns ApiInteractionBindMfaPostRequestOneOf2 wrapped in ApiInteractionBindMfaPostRequest
func ApiInteractionBindMfaPostRequestOneOf2AsApiInteractionBindMfaPostRequest(v *ApiInteractionBindMfaPostRequestOneOf2) ApiInteractionBindMfaPostRequest {
	return ApiInteractionBindMfaPostRequest{
		ApiInteractionBindMfaPostRequestOneOf2: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ApiInteractionBindMfaPostRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ApiInteractionBindMfaPostRequestOneOf
	err = newStrictDecoder(data).Decode(&dst.ApiInteractionBindMfaPostRequestOneOf)
	if err == nil {
		jsonApiInteractionBindMfaPostRequestOneOf, _ := json.Marshal(dst.ApiInteractionBindMfaPostRequestOneOf)
		if string(jsonApiInteractionBindMfaPostRequestOneOf) == "{}" { // empty struct
			dst.ApiInteractionBindMfaPostRequestOneOf = nil
		} else {
			if err = validator.Validate(dst.ApiInteractionBindMfaPostRequestOneOf); err != nil {
				dst.ApiInteractionBindMfaPostRequestOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.ApiInteractionBindMfaPostRequestOneOf = nil
	}

	// try to unmarshal data into ApiInteractionBindMfaPostRequestOneOf1
	err = newStrictDecoder(data).Decode(&dst.ApiInteractionBindMfaPostRequestOneOf1)
	if err == nil {
		jsonApiInteractionBindMfaPostRequestOneOf1, _ := json.Marshal(dst.ApiInteractionBindMfaPostRequestOneOf1)
		if string(jsonApiInteractionBindMfaPostRequestOneOf1) == "{}" { // empty struct
			dst.ApiInteractionBindMfaPostRequestOneOf1 = nil
		} else {
			if err = validator.Validate(dst.ApiInteractionBindMfaPostRequestOneOf1); err != nil {
				dst.ApiInteractionBindMfaPostRequestOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.ApiInteractionBindMfaPostRequestOneOf1 = nil
	}

	// try to unmarshal data into ApiInteractionBindMfaPostRequestOneOf2
	err = newStrictDecoder(data).Decode(&dst.ApiInteractionBindMfaPostRequestOneOf2)
	if err == nil {
		jsonApiInteractionBindMfaPostRequestOneOf2, _ := json.Marshal(dst.ApiInteractionBindMfaPostRequestOneOf2)
		if string(jsonApiInteractionBindMfaPostRequestOneOf2) == "{}" { // empty struct
			dst.ApiInteractionBindMfaPostRequestOneOf2 = nil
		} else {
			if err = validator.Validate(dst.ApiInteractionBindMfaPostRequestOneOf2); err != nil {
				dst.ApiInteractionBindMfaPostRequestOneOf2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.ApiInteractionBindMfaPostRequestOneOf2 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ApiInteractionBindMfaPostRequestOneOf = nil
		dst.ApiInteractionBindMfaPostRequestOneOf1 = nil
		dst.ApiInteractionBindMfaPostRequestOneOf2 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ApiInteractionBindMfaPostRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ApiInteractionBindMfaPostRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ApiInteractionBindMfaPostRequest) MarshalJSON() ([]byte, error) {
	if src.ApiInteractionBindMfaPostRequestOneOf != nil {
		return json.Marshal(&src.ApiInteractionBindMfaPostRequestOneOf)
	}

	if src.ApiInteractionBindMfaPostRequestOneOf1 != nil {
		return json.Marshal(&src.ApiInteractionBindMfaPostRequestOneOf1)
	}

	if src.ApiInteractionBindMfaPostRequestOneOf2 != nil {
		return json.Marshal(&src.ApiInteractionBindMfaPostRequestOneOf2)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ApiInteractionBindMfaPostRequest) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ApiInteractionBindMfaPostRequestOneOf != nil {
		return obj.ApiInteractionBindMfaPostRequestOneOf
	}

	if obj.ApiInteractionBindMfaPostRequestOneOf1 != nil {
		return obj.ApiInteractionBindMfaPostRequestOneOf1
	}

	if obj.ApiInteractionBindMfaPostRequestOneOf2 != nil {
		return obj.ApiInteractionBindMfaPostRequestOneOf2
	}

	// all schemas are nil
	return nil
}

type NullableApiInteractionBindMfaPostRequest struct {
	value *ApiInteractionBindMfaPostRequest
	isSet bool
}

func (v NullableApiInteractionBindMfaPostRequest) Get() *ApiInteractionBindMfaPostRequest {
	return v.value
}

func (v *NullableApiInteractionBindMfaPostRequest) Set(val *ApiInteractionBindMfaPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiInteractionBindMfaPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiInteractionBindMfaPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiInteractionBindMfaPostRequest(val *ApiInteractionBindMfaPostRequest) *NullableApiInteractionBindMfaPostRequest {
	return &NullableApiInteractionBindMfaPostRequest{value: val, isSet: true}
}

func (v NullableApiInteractionBindMfaPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiInteractionBindMfaPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


