/*
Logto API references

API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.

API version: Cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package logto

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateOrganizationJitSsoConnectorRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrganizationJitSsoConnectorRequest{}

// CreateOrganizationJitSsoConnectorRequest struct for CreateOrganizationJitSsoConnectorRequest
type CreateOrganizationJitSsoConnectorRequest struct {
	// The SSO connector IDs to add.
	SsoConnectorIds []string `json:"ssoConnectorIds"`
}

type _CreateOrganizationJitSsoConnectorRequest CreateOrganizationJitSsoConnectorRequest

// NewCreateOrganizationJitSsoConnectorRequest instantiates a new CreateOrganizationJitSsoConnectorRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrganizationJitSsoConnectorRequest(ssoConnectorIds []string) *CreateOrganizationJitSsoConnectorRequest {
	this := CreateOrganizationJitSsoConnectorRequest{}
	this.SsoConnectorIds = ssoConnectorIds
	return &this
}

// NewCreateOrganizationJitSsoConnectorRequestWithDefaults instantiates a new CreateOrganizationJitSsoConnectorRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrganizationJitSsoConnectorRequestWithDefaults() *CreateOrganizationJitSsoConnectorRequest {
	this := CreateOrganizationJitSsoConnectorRequest{}
	return &this
}

// GetSsoConnectorIds returns the SsoConnectorIds field value
func (o *CreateOrganizationJitSsoConnectorRequest) GetSsoConnectorIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.SsoConnectorIds
}

// GetSsoConnectorIdsOk returns a tuple with the SsoConnectorIds field value
// and a boolean to check if the value has been set.
func (o *CreateOrganizationJitSsoConnectorRequest) GetSsoConnectorIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SsoConnectorIds, true
}

// SetSsoConnectorIds sets field value
func (o *CreateOrganizationJitSsoConnectorRequest) SetSsoConnectorIds(v []string) {
	o.SsoConnectorIds = v
}

func (o CreateOrganizationJitSsoConnectorRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrganizationJitSsoConnectorRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ssoConnectorIds"] = o.SsoConnectorIds
	return toSerialize, nil
}

func (o *CreateOrganizationJitSsoConnectorRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ssoConnectorIds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOrganizationJitSsoConnectorRequest := _CreateOrganizationJitSsoConnectorRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateOrganizationJitSsoConnectorRequest)

	if err != nil {
		return err
	}

	*o = CreateOrganizationJitSsoConnectorRequest(varCreateOrganizationJitSsoConnectorRequest)

	return err
}

type NullableCreateOrganizationJitSsoConnectorRequest struct {
	value *CreateOrganizationJitSsoConnectorRequest
	isSet bool
}

func (v NullableCreateOrganizationJitSsoConnectorRequest) Get() *CreateOrganizationJitSsoConnectorRequest {
	return v.value
}

func (v *NullableCreateOrganizationJitSsoConnectorRequest) Set(val *CreateOrganizationJitSsoConnectorRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrganizationJitSsoConnectorRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrganizationJitSsoConnectorRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrganizationJitSsoConnectorRequest(val *CreateOrganizationJitSsoConnectorRequest) *NullableCreateOrganizationJitSsoConnectorRequest {
	return &NullableCreateOrganizationJitSsoConnectorRequest{value: val, isSet: true}
}

func (v NullableCreateOrganizationJitSsoConnectorRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrganizationJitSsoConnectorRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


