/*
Logto API references

API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.

API version: Cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package logto

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest{}

// ApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest struct for ApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest
type ApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest struct {
	State string `json:"state"`
	// Validator function
	RedirectUri map[string]interface{} `json:"redirectUri"`
}

type _ApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest ApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest

// NewApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest instantiates a new ApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest(state string, redirectUri map[string]interface{}) *ApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest {
	this := ApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest{}
	this.State = state
	this.RedirectUri = redirectUri
	return &this
}

// NewApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequestWithDefaults instantiates a new ApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequestWithDefaults() *ApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest {
	this := ApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest{}
	return &this
}

// GetState returns the State field value
func (o *ApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *ApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *ApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest) SetState(v string) {
	o.State = v
}

// GetRedirectUri returns the RedirectUri field value
func (o *ApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest) GetRedirectUri() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.RedirectUri
}

// GetRedirectUriOk returns a tuple with the RedirectUri field value
// and a boolean to check if the value has been set.
func (o *ApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest) GetRedirectUriOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.RedirectUri, true
}

// SetRedirectUri sets field value
func (o *ApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest) SetRedirectUri(v map[string]interface{}) {
	o.RedirectUri = v
}

func (o ApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["state"] = o.State
	toSerialize["redirectUri"] = o.RedirectUri
	return toSerialize, nil
}

func (o *ApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"state",
		"redirectUri",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest := _ApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest)

	if err != nil {
		return err
	}

	*o = ApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest(varApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest)

	return err
}

type NullableApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest struct {
	value *ApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest
	isSet bool
}

func (v NullableApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest) Get() *ApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest {
	return v.value
}

func (v *NullableApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest) Set(val *ApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest(val *ApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest) *NullableApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest {
	return &NullableApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest{value: val, isSet: true}
}

func (v NullableApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiInteractionSingleSignOnConnectorIdAuthorizationUrlPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


