name: Commitlint

on:
  push:
    branches:
      - 'push-action/**'
  pull_request:
    types: [opened, edited, synchronize, reopened]

concurrency: 
  group: commitlint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-commits:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install commitlint tools
        run: |
          npm install -g @commitlint/config-conventional @commitlint/cli
          npm link @commitlint/config-conventional
      
      - name: Create commitlint config file
        run: |
          cat <<EEE > commitlint.config.mjs
          export default {
            extends: ["@commitlint/config-conventional"],
            rules: {
              "type-enum": [
                2,
                "always",
                [
                  "feat",
                  "fix",
                  "refactor",
                  "test",
                  "ci",
                  "chore",
                  "revert",
                  "release",
                ],
              ],
              "scope-enum": [2, "always", ["core", "client", "gin-sample", "deps"]],
              "body-max-line-length": [2, "always", 200],
            },
          };
          EEE

      - name: Commitlint
        run: npx commitlint --from HEAD~${{ github.event.pull_request.commits }} --to HEAD

      - name: Commitlint on PR title
        run: echo '${{ github.event.pull_request.title }}' | npx commitlint
